// <auto-generated />
namespace dnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class armor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(armor));
        
        string IMigrationMetadata.Id
        {
            get { return "202111271853231_armor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
